### ISSUE TITLE
Problems adding more than one page to a document

### ISSUE THREAD

**Issue by textPreferred** [jflesch/paperwork#375] opened 2015-05-07 08:24 UTC
Creating a document by scanning the first page is fine. OCR fires and it is added as a "page" to the document.

When scanning the second page, things go all wrong:
- OCR process not shown in the UI
- page is not added to the document cf. screenshot
- page is shown in low-res (OCR) quality, cf. screenshot
- the progress bar in the lower left stays at 0% which looks very suspicious

Misc. information:
- Issue may be connected to updating my Ubuntu system.
- I have updated paperwork ("sude pip install --update paperwork") but this did not help.

Please find a screenshot and the console output below.

![paperwork_problem_with_second_page](https://cloud.githubusercontent.com/assets/1721427/7511160/316d1424-f4a3-11e4-929d-3ceb17c84033.png)

```
INFO   paperwork.frontend.mainwindow.scan Scan done
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Cuneiform'
INFO   paperwork.frontend.mainwindow.scan Failed to use OCR tool heuristic for orientation detection: OCR tool does not support orientation detection
INFO   paperwork.frontend.mainwindow.scan Falling back on Paperwork's heuristic
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (88, 400) (600, 830) -> (74, 433) (240, 348)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 90: (88, 400) (600, 830) -> (462, 433) (240, 348)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 180: (88, 400) (600, 830) -> (74, 848) (240, 348)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 270: (88, 400) (600, 830) -> (462, 848) (240, 348)
INFO   paperwork.frontend.mainwindow.scan Starting OCR on angle 0
INFO   paperwork.frontend.mainwindow.scan Running OCR on page orientation 0
INFO   paperwork.frontend.mainwindow.scan Starting OCR on angle 90
INFO   paperwork.frontend.mainwindow.scan Running OCR on page orientation 1
INFO   paperwork.frontend.mainwindow.scan Starting OCR on angle 180
INFO   paperwork.frontend.mainwindow.scan Running OCR on page orientation 2
INFO   paperwork.frontend.mainwindow.scan Starting OCR on angle 270
INFO   paperwork.frontend.mainwindow.scan Running OCR on page orientation 3
INFO   paperwork.frontend.mainwindow.scan Evaluating score of page orientation (0) using method 'spell_checker' ...
INFO   paperwork.frontend.mainwindow.scan Evaluating score of page orientation (3) using method 'spell_checker' ...
INFO   paperwork.frontend.mainwindow.scan Evaluating score of page orientation (2) using method 'spell_checker' ...
INFO   paperwork.frontend.mainwindow.scan Evaluating score of page orientation (1) using method 'spell_checker' ...
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 0: 435.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 270: 5.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 180: 45.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 90: 205.000000
INFO   paperwork.frontend.mainwindow.scan Best: 435.000000
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 25264ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.util.canvas Animators: 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas Animators: 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 208, in __on_draw
    drawer.draw(cairo_ctx)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 197, in draw
    (self.frame % self.nb_frames[0]),
ZeroDivisionError: integer division or modulo by zero
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   root                           Showing page 20150506_2022_10 p1
INFO   paperwork.frontend.util.actions Action: [Label selected]
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   root                           Showing page 20150506_2022_10 p1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   root                           Showing page 20150506_2022_10 p1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow  Showing doc 20150506_2022_10
INFO   paperwork.frontend.mainwindow  Doc is already shown
```

**Comment by jflesch** [comment] 2015-05-07 08:38
Interresting. Can you try again with the version in the branch 'stable' please ? I think it may have already been fixed because of #374 . (see https://github.com/jflesch/paperwork/blob/stable/doc/install.devel.markdown to install the stable version ; just replace "git checkout unstable" by "git checkout stable")

**Comment by textPreferred** [comment] 2015-05-07 09:03
I have no experience with Python, so I am not sure I tested it correctly. 
Here's what I did:
- clone the paperwork Git repo to a local folder
- locally checked out "unstable"
(git status tells me I am
"On branch unstable
Your branch is up-to-date with 'origin/unstable'.")

Moved to "paperwork/scripts".

Started "./paperwork".

Same issue as before.

Then I explicitly checked out commit 7660ae4ead889151c8021a2842c1da1794600e86, ran "./scripts/paperwork". 

Still the same problem.

**Comment by textPreferred** [comment] 2015-05-07 09:04
Sorry, I did not see your instructions on how to test. Will follow these now.

**Comment by textPreferred** [comment] 2015-05-07 09:21
No change, I am afraid. Same issue as before.

The console log still contains this line: 
"WARNING paperwork.frontend.util.jobs   Job OCR:0 took 29573ms and is unstoppable ! (maximum allowed: 500ms)"

**Comment by jflesch** [comment] 2015-05-07 09:23
To clarify a bit:

```
$ git clone https://github.com/jflesch/paperwork.git
$ cd paperwork
$ git checkout stable
$ sudo python ./setup.py install
$ paperwork-chkdeps
$ cd ~
$ paperwork
```

Later, to update:

```
$ cd paperwork
$ git pull
$ sudo python ./setup.py install
$ paperwork-chkdeps
```

To uninstall (note that it won't uninstall dependencies :/):

```
$ sudo pip uninstall paperwork
# you may have to run it many times
```

**Comment by jflesch** [comment] 2015-05-07 09:24
By the way, don't worry about this warning. It just mean that the UI could remain frozen while the OCR is running. It's a known problem.

**Comment by textPreferred** [comment] 2015-05-07 09:29
paperwork-chkdeps shows something:

```
[WARN] Unable to figure out the exact language package to install
[WARN] OCR language data not found
[WARN] Dictionnary '<your language>' not found

WARNING: Missing dependencies:
  - Tesseract language data (python module: (none) ; ubuntu package : tesseract-ocr-<your language>)
  - Dictionary (python module: (none) ; ubuntu package : aspell-<your language>)

Suggested command:
  sudo apt-get install tesseract-ocr-<your language> aspell-<your language>
Do you want to run this command now ? [Y/n]
Y
sh: 1: Syntax error: end of file unexpected
```

However, if I run 
"sudo apt-get install tesseract-ocr-deu aspell-de" (for German OCR and wordlist), I am told that both are already the newest version.

**Comment by jflesch** [comment] 2015-05-07 09:34
Hm, the output of paperwork-chkdeps is weird. I'll have a look asap.
However it's not related to your issue. I'll make a workaround for now and see later if I can find why this bug occurs.

**Comment by jflesch** [comment] 2015-05-07 09:38
98f65dad9bcd8eabee51e24dbdc1b22d6bdffebe

Please update (git pull) and tell me if it works (for now, I cannot test myself :/).

**Comment by jflesch** [comment] 2015-05-07 09:41
Which version of Ubuntu are you using exactly ?

**Comment by textPreferred** [comment] 2015-05-07 09:49
(Kubuntu 15.04)

98f65da did the trick!

paperwork-chkdeps still complains about missing OCR and spelling, but running paperwork and scanning additional pages works fine:
- the scanning works
- the display of the four orientations works
- the page is added properly to the document
- the preview is good.

Thank you!

**Comment by jflesch** [comment] 2015-05-07 11:47
You're welcome.

I'll keep the ticket open for now because:
* I must find what was the root cause of this problem
* I need to see why paperwork-chkdeps is not working correctly anymore on Ubuntu

**Comment by jflesch** [comment] 2015-11-17 12:59
Hm, can you run ```paperwork-chkdeps -v``` and post the output here please ? It seems the script didn't detect correctly your locale.

**Comment by jflesch** [comment] 2015-12-01 16:36
Ping ?

**Comment by textPreferred** [comment] 2015-12-02 07:32
Pong :)

I should be able to test within the next 7 days.

**Comment by jflesch** [comment] 2015-12-22 22:35
ping ?

**Comment by jflesch** [comment] 2016-01-02 14:43
No reply, so I assume I'm not going to get the output of ```paperwork-chkdeps -v```` ... I'm closing this ticket.

**Comment by courseraccount** [comment] 2016-01-03 07:56
Sorry. The output is as follows:

"Error reading directory:

UnrecoverableFileError: the directory (or mutable file) could not be retrieved, because there were insufficient good shares. This might indicate that no servers were connected, insufficient servers were connected, the URI was corrupt, or that shares have been lost due to server departure, hard drive failure, or disk corruption. You should perform a filecheck on this object to learn more."

**Comment by courseraccount** [comment] 2016-01-03 07:57
I am sorry.

The output is as follows:

"Detected python version: 2.7.10.final.0
Detected system: Ubuntu 15.10 wily
Detected language: en
[WARN] Unable to figure out the exact language package to install
Looking for Python GObject Introspection ...
Looking for Gtk ...
Looking for Glade UI ...
Looking for Poppler ...
Looking for Cairo ...
Looking for OCR tool ...
Looking for OCR language data ...
[WARN] OCR language data not found
Looking for dictionnary '<your language>'
[WARN] Dictionnary '<your language>' not found


WARNING: Missing dependencies:
  - Tesseract language data (python module: (none) ; ubuntu package : tesseract-ocr-<your language>)
  - Dictionary (python module: (none) ; ubuntu package : aspell-<your language>)

Suggested command:
  sudo apt-get install tesseract-ocr-<your language> aspell-<your language>
Do you want to run this command now ? [Y/n]
y
sh: 1: Syntax error: end of file unexpected"

**Comment by textPreferred** [comment] 2016-01-03 08:00
I am sorry.

Here it is:

"Detected python version: 2.7.10.final.0
Detected system: Ubuntu 15.10 wily
Detected language: en
[WARN] Unable to figure out the exact language package to install
Looking for Python GObject Introspection ...
Looking for Gtk ...
Looking for Glade UI ...
Looking for Poppler ...
Looking for Cairo ...
Looking for OCR tool ...
Looking for OCR language data ...
[WARN] OCR language data not found
Looking for dictionnary '<your language>'
[WARN] Dictionnary '<your language>' not found


WARNING: Missing dependencies:
  - Tesseract language data (python module: (none) ; ubuntu package : tesseract-ocr-<your language>)
  - Dictionary (python module: (none) ; ubuntu package : aspell-<your language>)

Suggested command:
  sudo apt-get install tesseract-ocr-<your language> aspell-<your language>
Do you want to run this command now ? [Y/n]
y
sh: 1: Syntax error: end of file unexpected"

**Comment by jflesch** [comment] 2016-01-03 12:01
Hm, I think you're not fully up-to-date.
Anyway, it seems I was so focused on french and german locales, I forgot to support english locale ... It should be fixed now (in the branch 'testing'):

Where you run ```git clone (...)paperwork``` previously, can you run the following commands please ?

````
git checkout testing
git pull
scripts/paperwork -v
````

**Comment by textPreferred** [comment] 2016-01-03 12:12
Works!

Here's the output:

"Detected python version: 2.7.10.final.0
Detected system: Ubuntu 15.10 wily
Detected language: en
Looking for Python GObject Introspection ...
Looking for Gtk ...
Looking for Glade UI ...
Looking for Poppler ...
Looking for Cairo ...
Looking for OCR tool ...
Looking for OCR language data ...
Looking for dictionnary 'en'

All dependencies have been found."

**Comment by jflesch** [comment] 2016-01-03 12:33
Awesome :)
Thanks for your bug report, and happy new year to you ;)

**Closed by jflesch** 2016-01-03 12:33 UTC
Labels: bug, to study
