### ISSUE TITLE
[v0.2.x] OCR failure on portrait PDF files upon reaching a 90°-rotated landscape page.

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#408] opened 2015-10-17 13:39 UTC
I have PDF files produced by a scanner with feeder. Most pages have a portrait orientation.
Some pages, however, while still having been scanned in portait orientation, are actually landscape pages that have been rotated by 90° in order to align with other pages in the feeder. When reaching such a page, the OCR stops in error.
Here’s an example log, with page 31 being a rotated landscape page:
```
…
INFO   paperwork.frontend.mainwindow  Redoing OCR on 20151017_1439_54 p29
INFO   paperwork.frontend.mainwindow  Showing document 20151017_1439_54
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   root                           Showing page 20151017_1439_54 p1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   paperwork.frontend.util.progressivelist List 'pages' : 98 elements displayed (98 additionnal)
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract'
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (0, 28028) (620, 876) -> (108, 28140) (456, 653)
INFO   paperwork.frontend.mainwindow.scan Detected orientation: 0
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 19132ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.mainwindow  Redoing OCR on 20151017_1439_54 p30
INFO   paperwork.frontend.mainwindow  Showing document 20151017_1439_54
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   root                           Showing page 20151017_1439_54 p1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   paperwork.frontend.util.progressivelist List 'pages' : 98 elements displayed (98 additionnal)
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract'
INFO   paperwork.frontend.mainwindow.scan Detected orientation: 0
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (0, 29029) (620, 876) -> (108, 29141) (456, 653)
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 3328ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.mainwindow  Redoing OCR on 20151017_1439_54 p31
INFO   paperwork.frontend.mainwindow  Showing document 20151017_1439_54
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   root                           Showing page 20151017_1439_54 p1
INFO   paperwork.frontend.util.actions Action: [Show a page (selected from the page thumbnail list)]
INFO   paperwork.frontend.util.progressivelist List 'pages' : 98 elements displayed (98 additionnal)
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract'
INFO   paperwork.frontend.mainwindow.scan Detected orientation: 270
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (0, 30030) (620, 876) -> (108, 30142) (456, 653)
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 9397ms and is unstoppable ! (maximum allowed: 500ms)
Traceback (most recent call last):
  File "/ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/mainwindow/scan.py", line 653, in __on_ocr_done_cb
    drawers = self.ocr_drawers[angle]
KeyError: 270
```
_(logs stop here)_

**Comment by jflesch** [comment] 2016-02-16 11:41
Duplicate of #406

**Closed by jflesch** 2016-02-16 11:41 UTC
