### ISSUE TITLE
feature request: easier scrolling to old documents

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#397] opened 2015-10-01 11:05 UTC
I now have 1107 documents in Paperwork. Often, I need old documents, and I find myself hitting the "End" key dozens of times (and waiting between each keystroke because the list is then refreshed).

I have to do this because:
— either the keyword/label search did not help (this happens with so many documents);
— or I need access to a whole "story" of mostly consecutive documents that do not share the same keywords/labels;
— or I have to find a document, the date of which I changed to a long-past date, and then later I realize I forgot to set the right labels on this document…

Some small enhancements would greatly help:
— After a search is done, and the focus is placed on an old document, and the search bar is cleared (in order to view all documents), it would be nice if the document list would centre on the focused document (same goes after the date of the focused document is changed, by the way).
— It would be nice to be able to search for a year, or a year-month. Then, in combination with the above wish item, this would allow a two-step narrowing (filter on date then browse).

Please feel free to discuss/improve/etc.

**Comment by jflesch** [comment] 2015-10-01 13:17
> — After a search is done, and the focus is placed on an old document, and the search bar is cleared (in order to view all documents), it would be nice if the document list would centre on the focused document (same goes after the date of the focused document is changed, by the way).

#224 

> — It would be nice to be able to search for a year, or a year-month. Then, in combination with the above wish item, this would allow a two-step narrowing (filter on date then browse).

It is already possible. If you let your mouse over the search field, a tooltip should appear, showing possible advanced searches (however this tooltip tends to bug ...).

Content of the popup:
```
Search documents
  * To search documents with a specific label: label:[label]
  * Only the documents with a specific keyword: "[keyword]"
  * Ignore documents containing a specific keyword: NOT [keyword]
  * Find documents with one word or another: [keyword] OR [keyword]
  * Documents with a specific date: date:YYYYMMDD or date:[YYYYMMDD to YYYYMMDD]
```

I know it is something that is not intuitive *at* *all*. A dialog will be added later to make those complex searches more easily ( #193 ).

**Comment by jflesch** [comment] 2015-11-14 23:25
Duplicate of #224 and #193.
Please feel free to reopen if not

**Closed by jflesch** 2015-11-14 23:25 UTC
Labels: gui improvement
