### ISSUE TITLE
GtkSettings issue

### ISSUE THREAD

**Issue by majordom21** [jflesch/paperwork#443] opened 2016-02-17 15:25 UTC
hello, 

I'm new on paperwork. Using your instalation note for Ubuntu, I finally have this error

``INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file not found. Will use '/home/dom/.config/paperwork.conf'
INFO   paperwork.backend.config       Reloading /home/dom/.config/paperwork.conf ...
ERROR  paperwork.frontend.util.config Warning: Failed to figure out system language (locale is [en_US]). Will default to eng
ERROR  paperwork.frontend.util.config Exception was: 'alpha2'
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1859, in __init__
    self.__init_headerbars()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2288, in __init_headerbars
    default_layout = settings.get_property("gtk-decoration-layout")
TypeError: object of type `GtkSettings' does not have property `gtk-decoration-layout'``

Do you have any idea? Did I miss something ?

thanx

**Comment by jflesch** [comment] 2016-02-17 16:00
Ubuntu LTS I guess ?
Then it's a duplicate of #441 and #440 .

**Closed** 2016-02-17 16:00 UTC

**Comment by majordom21** [comment] 2016-02-18 07:48
Yes, Ubuntu LTS

but changing the 3.14 in 3.10 in the glades files doesn't solve the problem.

thanx for your answer. I'll still follow the thread until someone find the
soluton

2016-02-17 17:00 GMT+01:00 Jerome Flesch <notifications@github.com>:

> Closed #443 <https://github.com/jflesch/paperwork/issues/443>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jflesch/paperwork/issues/443#event-553768658>.
>



-- 
--

*SERVELLE Dominique*

11, rue courtépée

21000 DIJON



tel : 06 78 03 40 14

www.majordom21.org
