### ISSUE TITLE
browsing file through gi.repository.Gio

### ISSUE THREAD

**Issue by jaesivsm** [jflesch/paperwork#367] opened 2015-02-23 23:07 UTC
We could use the gnome layer (http://www.pygtk.org/docs/pygobject/gio-class-reference.html) to access all kind of mount types (sshfs, davs, smb). 
For the very light investigation I made until now, the implementation may not be very easy but I'd be glade to work on a patch.

**Comment by jflesch** [comment] 2015-02-23 23:12
Duplicate of #21

**Closed by jflesch** 2015-02-23 23:12 UTC

**Comment by jflesch** [comment] 2015-02-23 23:13
If you have time, feel free to send a patch. It would spare me time.

**Comment by jaesivsm** [comment] 2015-02-23 23:49
Oh sorry, I thought I checked for duplicate better than that. I'm not promising anything quick, but I have a good example of implementation in the duplicity software. I might get something out of this.
