### ISSUE TITLE
paperwork launch a game called tesseract ?

### ISSUE THREAD

**Issue by teto** [jflesch/paperwork#604] opened 2017-02-22 13:50 UTC
I have a game called tesseract (http://tesseract.gg/) and I was surprised to see paperwork launch the game xD ? here is the trace:

```
WARNING paperwork.paperwork            No suitable localization file found.
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_ikq5sz6o/pipe_c2s | /tmp/pyinsane_ikq5sz6o/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file not found. Will use '/home/teto/.config/paperwork.conf'
INFO   paperwork_backend.config       Reloading /home/teto/.config/paperwork.conf ...
/home/teto/.local/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py:2779: Warning: g_set_application_name() called multiple times
  GLib.set_application_name(_("Paperwork"))
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/home/teto/.local/bin/paperwork", line 6, in <module>
    main()
  File "/home/teto/.local/lib/python3.5/site-packages/paperwork/paperwork.py", line 144, in main
    main_win = MainWindow(config)
  File "/home/teto/.local/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2297, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/home/teto/.local/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2826, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/home/teto/.local/lib/python3.5/site-packages/paperwork/frontend/util/__init__.py", line 144, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
ERROR  paperwork.frontend.diag        ===========================
```

also please support pip install --user.

**Comment by tiramiseb** [comment] 2017-02-22 14:00
Tesseract is the OCR software used by paperwork.
Developers of this game could have chosen a name which is not already used elsewhere :)

I personally don't have a solution for you.
Maybe there should be a way to define tesseract path in the configuration...

**Comment by jflesch** [comment] 2017-02-22 14:21
A solution would be to patch pyocr to use the libtesseract instead of the command tesseract:

```sh
cd /tmp
git clone https://github.com/jflesch/pyocr
cd pyocr
patch -p1 << EOF
diff --git a/src/pyocr/pyocr.py b/src/pyocr/pyocr.py
index f73863f..cc3c828 100755
--- a/src/pyocr/pyocr.py
+++ b/src/pyocr/pyocr.py
@@ -57,7 +57,7 @@ __all__ = [
 
 
 TOOLS = [  # in preference order
-    tesseract,
+    # tesseract,
     libtesseract,
     cuneiform,
 ]
EOF
sudo python3 ./setup.py install
```

**Comment by tiramiseb** [comment] 2017-02-22 14:23
Out of curiosity... Why would it use the tesseract command instead of the lib ? What is the advantage ?

**Comment by jflesch** [comment] 2017-02-22 14:24
Anyway, this is not an issue with Paperwork nor PyOCR but with your game, so I'm closing this ticket.
If you decide to report this issue to the game creators, my advise for them would be to just change the name of their command (for instance ```tesseract-game``` instead of just ```tesseract```).

**Comment by tiramiseb** [comment] 2017-02-22 14:25
I don't agree @jflesch : you can't rely on the command name or location. Tesseract may be outside of the PATH, or a maintainer may change the command name...

I think allowing to define the path may be useful, event if there is no GUI for that but only a config var...

**Comment by jflesch** [comment] 2017-02-22 14:25
@tiramiseb some people reported instability with libtesseract. And when it causes a segfault, Paperwork itself crashes with it :(
So I've moved it down the list for now .. but since I can't reproduce these issues, I don't know when I'll be able to move it back up ... Maybe I'll have to workaround these crashes by using the python module ```multiprocessing``` ... :/

**Comment by tiramiseb** [comment] 2017-02-22 14:27
Regarding tesseract in the PATH etc, https://github.com/jflesch/pyocr/blob/master/src/pyocr/tesseract.py#L32 show that there may be problems that would only be solved by modifying sourcecode, which is not a good solution

**Comment by jflesch** [comment] 2017-02-22 14:27
Agreed, but then it's a ticket for PyOCR, not Paperwork ;)

**Comment by jflesch** [comment] 2017-02-22 14:27
Anyway, I'm closing this ticket

**Closed by jflesch** 2017-02-22 14:27 UTC
Labels: support

**Comment by teto** [comment] 2017-02-22 14:42
Of course it's a trivial problem no worry. Just it was funny to have this game I had forgotten it was even installed to launch.

More important is:

> please support pip install --user

It should be pretty straightforward, just fixing the setup.py to correctly access resources ?

**Comment by jflesch** [comment] 2017-02-22 15:07
> >    please support pip install --user
> It should be pretty straightforward

Hm, not sure. I added those weird ```os.path.join(sys.prefix, ``` a very long time ago for a reason, and I don't remember exactly why. Maybe due to a bug in old versions of Pip (or maybe just because I'm not familiar enough with Python resources .. ). I'm going to look at the git history later.
It may require also changes in ```src/paperwork/frontend/util/__init__.py``` (all the ```load_xxx()``` and ```get_documentation()``` functions).

Also I don't use ```--user``. So if you're familiar with Python / setuptools, feel free to give it a try. It would probably work best if done by someone actually using it.

**Comment by teto** [comment] 2017-02-22 15:18
Actually I might give it a try. This is my first time using paperwork
(found from linuxfr) and apart from few bugs (removing a document makes
everything disappear) I must admit it's quite cool. Congrats.

2017-02-22 16:07 GMT+01:00 Jerome Flesch <notifications@github.com>:

**Comment by jflesch** [comment] 2017-02-22 15:22
> removing a document makes everything disappear

Uh ? That's a regression then :(

**Comment by teto** [comment] 2017-02-22 15:29
so far using pip version 1.1.1 . I'll try master.

2017-02-22 16:22 GMT+01:00 Jerome Flesch <notifications@github.com>:

**Comment by teto** [comment] 2017-02-22 17:18
I successfully installed paperwork in develop mode so I suppose --user mode now works out of the box.
I had to modify paperwork-backend though since the pip version didn't match paperwork master requirements:
https://github.com/jflesch/paperwork-backend/pull/4

With this version removing a document works correctly :)

**Comment by jstenback** [comment] 2017-02-23 05:15
FWIW I see the everything disappears when deleting a document issue in 1.1.2 as well.

**Comment by jflesch** [comment] 2017-02-23 09:33
I've just created the ticket #607 for this issue.

To fix this bug, I'm going to need some information::
- the GNU/Linux distribution you use
- how many documents you have (I don't need an exact number, an approximation is good enough)
- if possible, the diagnostic output *after* you reproduced this issue would be even better ( https://openpaper.work/fr/helpdesk/kb/1/ )

(please post it on #607 so I can keep track of it easily)

**Comment by teto** [comment] 2017-02-24 13:33
After checking I couldn't install paperwork in develop mode and had to do install paperwork systemwide because of the data_files excepted in /usr/share.
I meet several problems (like I have to reboot paperwork for every scan because of https://github.com/jflesch/paperwork/issues/606, printing takes > 10min with errors etc) that I might be able to help with but being able to run in develop mode would be helpful.
The main obstacle for it though is the system wide install of *.glade files through "data_files". Every page I saw recommanded to not use this type of install. While I agree data files should be separated from the source code, there seems to be no good way to do so. The *best* way seems to be using package_data instead in setup.py like twisted does. Would you have any objection against this ?

**Comment by jflesch** [comment] 2017-02-24 13:52
No objections as long as things keep working :-)

**Comment by jflesch** [comment] 2017-02-24 13:56
In case it helps:

* if you move the files, you will probably have to fix / update functions in the module [util.py](https://github.com/jflesch/paperwork/blob/unstable/src/paperwork/frontend/util/__init__.py#L44)
* There are some resources that are accessed by Gtk itself. Mostly Paperwork icon (paperwork.svg) I think:
  * [main window](https://github.com/jflesch/paperwork/blob/unstable/src/paperwork/frontend/mainwindow/mainwindow.glade#L207)
  * [about dialog](https://github.com/jflesch/paperwork/blob/unstable/src/paperwork/frontend/aboutdialog/aboutdialog.glade#L731)
