### ISSUE TITLE
[idea] “insert document-break” button, for use after importing a folder of scanned images

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#540] opened 2016-11-25 09:33 UTC
Importing a folder of images is very convenient. However, I often have this situation where I scan dozens of pages on a better scanner than mine, and then import then when I’m back home; and these images are many documents in a row, not a single document.

What would be helpful, without complicating the Scan/Import menu in the least, would be a new tool that would be applicable to images-based document, thus _after_ import. This tool would act on the multi-page view and would allow to split the document: all pages after the cut-location would get moved to a new document with the same date+time, and would be treated as any new multi-images import: auto-detect label, etc.

Graphically, I suppose it is enough to have a vertical dotted line follow the mouse location, but locked to the grid formed by the multi-page view, eg:

```
+---+   +---+   +---+   +---+
| p |   | p |   | p |   | p |
| 1 |   | 2 |   | 3 |   | 4 |
+---+   +---+   +---+   +---+

+---+ ¦ +---+   +---+   +---+
| p | ¦ | p |   | p |   | p |
| 5 | ¦ | 6 |   | 7 |   | 8 |
+---+ ¦ +---+   +---+   +---+
```

**Comment by mjourdan** [comment] 2016-11-25 17:56
Yep, I also think this is a use case we should cover.

Multiple page selections #132 feels more intuitive to me to solve this issue, and would allow to easily sort your pages too.

**Comment by tYYGH** [comment] 2016-11-25 18:13
Agreed!

**Comment by jflesch** [comment] 2016-11-28 17:59
Agreed too :)

I'm going to consider this ticket as a duplicate of #132 and close it.
If not, please comment again, and I'll reopen it.

**Closed by jflesch** 2016-11-28 17:59 UTC
