### ISSUE TITLE
ERROR  paperwork.frontend.multiscan.scan Scan failed

### ISSUE THREAD

**Issue by zo34** [jflesch/paperwork#490] opened 2016-08-18 04:33 UTC
I'm attempting to scan a two-sided document, but paperwork hangs when paperwork.frontend.multiscan.scan is called. I've attached the command line output below-the relevant bit is toward the bottom.

```
(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
INFO   paperwork.frontend.util.actions Action: [Delete document]
INFO   paperwork.frontend.util.actions Action: [New document]
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow.docs Showing doc 20160817_2305_13
INFO   paperwork.frontend.mainwindow.docs Deleting ...
INFO   paperwork.frontend.util.actions Action: [New document]

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
INFO   paperwork.frontend.mainwindow  Showing document 20160817_2305_13
INFO   paperwork.backend.docsearch    Removing doc from the index: 20160511_0000_01

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.backend.docsearch    Index: Commiting changes
INFO   paperwork.backend.common.doc   Destroying doc: /home/chickens/papers/20160511_0000_01
INFO   paperwork.backend.util         Deleting file /home/chickens/papers/20160511_0000_01/paper.1.jpg
INFO   paperwork.backend.util         Deleting file /home/chickens/papers/20160511_0000_01/extra.txt
INFO   paperwork.backend.util         Deleting file /home/chickens/papers/20160511_0000_01/labels
INFO   paperwork.backend.util         Deleting file /home/chickens/papers/20160511_0000_01/paper.1.words
INFO   paperwork.backend.util         Deleting file /home/chickens/papers/20160511_0000_01/paper.1.thumb.jpg
INFO   paperwork.backend.common.doc   Done
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow.docs Got 1 documents
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow.docs Showing doc 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow  Doc is already shown
INFO   paperwork.frontend.util.actions Action: [New document]
INFO   paperwork.frontend.mainwindow  Opening search dialog
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/searchdialog/searchdialog.glade
INFO   paperwork.frontend.searchdialog Starting from an empty search
INFO   paperwork.frontend.searchdialog Search line instantiated
INFO   paperwork.frontend.searchdialog Element changed
INFO   paperwork.frontend.searchdialog Set element: Text: []
INFO   paperwork.frontend.searchdialog Search: [""]
INFO   paperwork.frontend.mainwindow  Search dialog: cancelled
INFO   paperwork.frontend.util.actions Action: [Scan multiples pages]
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/multiscan/multiscan.glade
INFO   paperwork.frontend.util.actions Action: [Add doc to the multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [End doc edit in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Start doc edit in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [End doc edit in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Add doc to the multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Add doc to the multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Doc selected in multi-scan list]
INFO   paperwork.frontend.util.actions Action: [Start multi-scan]
INFO   paperwork.frontend.util.config Will scan using hpaio:/net/officejet_pro_8500_a910?ip=192.168.1.3&queue=false
INFO   paperwork.frontend.util.config Will scan at a resolution of 300
INFO   paperwork.frontend.util.scanner Setting scanner option 'source' to 'ADF'
INFO   paperwork.frontend.util.config Scanner mode set to 'Color'
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas Animators: 2
INFO   paperwork.frontend.mainwindow.scan Scan started
INFO   paperwork.frontend.mainwindow  Doc is already shown
INFO   paperwork.frontend.mainwindow  Showing document 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas.drawers Drawer: Target area: (200, 0) ((528, 732)) << (200, 0) ((528, 681))
INFO   paperwork.frontend.mainwindow.scan Scan done
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract (C-API)'
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (200, 0) (528, 681) -> (101, 21) (243, 325)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 90: (200, 0) (528, 681) -> (545, 21) (243, 325)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 180: (200, 0) (528, 681) -> (101, 387) (243, 325)
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 270: (200, 0) (528, 681) -> (545, 387) (243, 325)
INFO   paperwork.frontend.mainwindow.scan Detected orientation: 0
Error in boxClipToRectangle: box outside rectangle
Error in pixScanForForeground: invalid box
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 23792ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.backend.img.doc      Adding page 0 to 20160817_2305_13
INFO   paperwork.frontend.mainwindow  Predicted labels on document [20160817_2305_13]: [set([<paperwork.backend.labels.Label object at 0x7f6cf8025a50>])]
INFO   paperwork.frontend.mainwindow  Showing page 20160817_2305_13 p1
INFO   paperwork.frontend.mainwindow  Showing document 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow.scan Scan started
INFO   paperwork.frontend.mainwindow.docs Will redo thumbnails: [<paperwork.backend.img.doc.ImgDoc object at 0x7f6cf8d84890>]

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Doc is already shown
INFO   paperwork.frontend.mainwindow  Showing document 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.backend.docsearch    Indexing new doc: 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.util.canvas.drawers Drawer: Target area: (200, 1134) ((528, 732)) << (200, 1134) ((528, 681))
INFO   paperwork.backend.docsearch    Index: Commiting changes
ERROR  paperwork.frontend.util.jobs   ===> Job Scan:0 raised an exception: <type 'exceptions.StopIteration'>: 
ERROR  paperwork.frontend.util.jobs    0: /usr/lib/python2.7/site-packages/paperwork/frontend/util/jobs.py: L  178: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/lib/python2.7/site-packages/paperwork/frontend/mainwindow/scan.py: L   89: do
ERROR  paperwork.frontend.util.jobs    2: /usr/lib/python2.7/site-packages/pyinsane/abstract_th.py: L  146: read
ERROR  paperwork.frontend.util.jobs    3: /usr/lib/python2.7/site-packages/pyinsane/abstract_th.py: L   59: wait
ERROR  paperwork.frontend.util.jobs   ---> Job Scan:0 was started by:
ERROR  paperwork.frontend.util.jobs    0:   /usr/bin/paperwork: L    6: <module>
ERROR  paperwork.frontend.util.jobs    1: /usr/lib/python2.7/site-packages/paperwork/paperwork.py: L  114: main
ERROR  paperwork.frontend.util.jobs    2: /usr/lib/python2.7/site-packages/paperwork/frontend/multiscan/scan.py: L  103: start_scan_workflow
ERROR  paperwork.frontend.util.jobs    3: /usr/lib/python2.7/site-packages/paperwork/frontend/mainwindow/scan.py: L  947: scan_and_ocr
ERROR  paperwork.frontend.util.jobs    4: /usr/lib/python2.7/site-packages/paperwork/frontend/mainwindow/scan.py: L  871: scan
ERROR  paperwork.frontend.util.jobs    5: /usr/lib/python2.7/site-packages/paperwork/frontend/util/jobs.py: L  247: schedule
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
ERROR  paperwork.frontend.multiscan.scan Scan failed: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paperwork/frontend/multiscan/scan.py", line 74, in __on_error
    self.__main_win.refresh_page_list()
AttributeError: 'MainWindow' object has no attribute 'refresh_page_list'

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow.docs Got 2 documents
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow.docs Showing doc 20160817_2305_13
INFO   paperwork.frontend.util.canvas Animators: 0

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(paperwork:18087): Gtk-WARNING **: gtkwidget.c:4524: child-property-changed notification for GtkListBox(0x55a0ed2aa240) is not frozen
INFO   paperwork.frontend.mainwindow  Doc is already shown
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 0 documents [0-0]

(paperwork:18087): Gtk-WARNING **: Allocating size to GtkRevealer 0x55a0ed290300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by jflesch** [comment] 2016-08-18 08:36
Based on the logs, I assume it hangs when it is about to scan the second face of the page, right ?

**Comment by zo34** [comment] 2016-08-23 16:46
That is correct.

**Comment by jflesch** [comment] 2016-08-28 15:49
Sorry, but I can't reproduce (0.3.2 or 0.4).

However, in the version 0.4 (not released yet ; git branch 'unstable'), there has been a *lot* of changes related to Pyinsane. So it may be worth trying again with the version 0.4 when it will be released.

In the meantime, I'm closing this ticket. Please reopen another one when the version 0.4 will be released if the problem is still here.

**Closed by jflesch** 2016-08-28 15:49 UTC
Labels: bug, regression, to study
