### ISSUE TITLE
pip install didn't run / setup.py run

### ISSUE THREAD

**Issue by sigmahlm** [jflesch/paperwork#395] opened 2015-09-23 18:27 UTC
If i install with pip or pypi-install:

> sigma@deepthought:~$ paperwork
> INFO   paperwork.backend.config       Reloading /home/sigma/.config/paperwork.conf ...
> ERROR  root                           Can't find resource file 'mainwindow/appmenu.xml'. Aborting
> INFO   paperwork.paperwork            Good bye
> Traceback (most recent call last):
>   File "/usr/local/bin/paperwork", line 6, in <module>
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 109, in main
>     main_win = MainWindow(config)
>   File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2432, in > __init__
>     self.__init_app_menu(self.app)
>   File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 3046, in > __init_app_menu
>     app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
>   File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/__init__.py", line 65, in load_uifile
>     raise Exception("Can't find resource file '%s'. Aborting" % filename)
> Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting

With last release & setup.py install it works.

Ubuntu 15.04 tested on 2 (Xubuntu & Lubuntu)

**Comment by jflesch** [comment] 2015-11-17 13:34
I just tested in a VM with Kubuntu 15.10, and it seems to work fine.

**Comment by jflesch** [comment] 2015-11-18 11:57
I'm going to close this bug. Please reopen if you still have problems (with Kubuntu 15.10).

**Comment by PaulHuygen** [comment] 2016-01-01 15:29
I hope I may add something. I had the same problem on Xubuntu vs. 14.04 (lts that is not easy to upgrade). In my case it helped to make a symbolic link from:

/usr/local/lib/python2.7/dist-packages/usr/share/paperwork
to:
/usr/local/share/paperwork

Thanks,

Paul Huygen

**Comment by jflesch** [comment] 2016-01-01 19:07
Ok, that's something I can fix.
I would prefer if I could reproduce it, but thanks to your information, I can do without it.

**Comment by z0u** [comment] 2016-01-10 13:02
I just hit this bug on Debian Jessie, too. Linking as suggested by @PaulHuygen worked.

**Comment by jflesch** [comment] 2016-01-11 00:10
I hope to release 0.3.0 at the end of this month. So I'm simply going to move this ticket for 0.3.0.

**Comment by jflesch** [comment] 2016-01-20 10:45
Workaround: 4d83912dceb3c7de41319ab8da6ca448c5522227 (branch 'testing') (Until I figure out exactly what's going on here)
It will be available when I release Paperwork 0.3.0.

**Closed by jflesch** 2016-01-20 10:45 UTC
Labels: bug, to study

**Comment by sampablokuper** [comment] 2016-07-03 19:38
Similar problem here, also on Debian Jessie. In my case, I preferred to install locally (i.e. with `pip install --user`):

```
~$ pip install --user paperwork
Collecting paperwork
  Downloading paperwork-0.3.2.tar.gz (164kB)
    100% |████████████████████████████████| 174kB 411kB/s 
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib/python2.7/dist-packages (from paperwork)
Collecting pycountry (from paperwork)
  Downloading pycountry-1.20.tar.gz (5.0MB)
    100% |████████████████████████████████| 5.0MB 76kB/s 
Collecting pyenchant (from paperwork)
  Downloading pyenchant-1.6.6-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 539kB/s 
Requirement already satisfied (use --upgrade to upgrade): python-Levenshtein in ./.local/lib/python2.7/site-packages (from paperwork)
Collecting pyinsane>=1.3.8 (from paperwork)
  Downloading pyinsane-1.3.8.tar.gz
Collecting pyocr>=0.3.0 (from paperwork)
  Downloading pyocr-0.4.1.tar.gz
Collecting termcolor (from paperwork)
  Downloading termcolor-1.1.0.tar.gz
Collecting Whoosh (from paperwork)
  Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468kB)
    100% |████████████████████████████████| 471kB 282kB/s 
Collecting simplebayes (from paperwork)
  Downloading simplebayes-1.5.8-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./.local/lib/python2.7/site-packages (from python-Levenshtein->paperwork)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from pyocr>=0.3.0->paperwork)
Building wheels for collected packages: paperwork, pycountry, pyinsane, pyocr, termcolor
  Running setup.py bdist_wheel for paperwork ... done
  Stored in directory: /home/sampablokuper/.cache/pip/wheels/eb/d8/c9/9508a3c7f4b3759089173eb154c9427fd48a155d38a35f6270
  Running setup.py bdist_wheel for pycountry ... done
  Stored in directory: /home/sampablokuper/.cache/pip/wheels/16/01/07/8b63e20f017e2fa3781be866207dd2f528f8b79331adba4b0d
  Running setup.py bdist_wheel for pyinsane ... done
  Stored in directory: /home/sampablokuper/.cache/pip/wheels/ab/42/0f/c1f8c69b58ed47a6dfdc542f1b5cb4306e1798038abf0f2326
  Running setup.py bdist_wheel for pyocr ... done
  Stored in directory: /home/sampablokuper/.cache/pip/wheels/00/41/6d/01041878b997da951deb1eac1aec67926dab9fdda34b8d9051
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /home/sampablokuper/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
Successfully built paperwork pycountry pyinsane pyocr termcolor
Installing collected packages: pycountry, pyenchant, pyinsane, pyocr, termcolor, Whoosh, simplebayes, paperwork
Successfully installed Whoosh-2.7.4 paperwork-0.3.2 pycountry-1.20 pyenchant-1.6.6 pyinsane-1.3.8 pyocr-0.4.1 simplebayes-1.5.8 termcolor-1.1.0
~$ paperwork-chkdeps 
[WARN] Poppler is missing !
[WARN] OCR tool not found
[WARN] OCR language data not found

WARNING: Missing dependencies:
  - Poppler (python module: gi.repository.Poppler ; debian package : gir1.2-poppler-0.18)
  - Tesseract (python module: (none) ; debian package : tesseract-ocr)
  - Tesseract language data (python module: (none) ; debian package : tesseract-ocr-eng)

Suggested command:
  sudo apt-get install gir1.2-poppler-0.18 tesseract-ocr tesseract-ocr-eng
Do you want to run this command now ? [Y/n]
y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  liblept4 libopenjp2-7 libtesseract3 tesseract-ocr-equ tesseract-ocr-osd
The following NEW packages will be installed:
  gir1.2-poppler-0.18 liblept4 libopenjp2-7 libtesseract3 tesseract-ocr tesseract-ocr-eng tesseract-ocr-equ
  tesseract-ocr-osd
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 29.2 MB of archives.
After this operation, 79.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main libopenjp2-7 i386 2.1.0-2 [120 kB]
Get:2 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main gir1.2-poppler-0.18 i386 0.26.5-2+deb8u1 [32.9 kB]
Get:3 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main liblept4 i386 1.71-2.1+b2 [799 kB]
Get:4 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main libtesseract3 i386 3.03.03-1 [1,066 kB]            
Get:5 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main tesseract-ocr-eng all 3.02-2 [22.0 MB]             
Get:6 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main tesseract-ocr-osd all 3.02-2 [4,276 kB]            
Get:7 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main tesseract-ocr-equ all 3.02-2 [823 kB]              
Get:8 tor+http://vwakviie2ienjx6t.onion/debian/ jessie/main tesseract-ocr i386 3.03.03-1 [134 kB]              
Fetched 29.2 MB in 1min 43s (281 kB/s)                                                                         
Selecting previously unselected package libopenjp2-7:i386.
(Reading database ... 291516 files and directories currently installed.)
Preparing to unpack .../libopenjp2-7_2.1.0-2_i386.deb ...
Unpacking libopenjp2-7:i386 (2.1.0-2) ...
Selecting previously unselected package gir1.2-poppler-0.18.
Preparing to unpack .../gir1.2-poppler-0.18_0.26.5-2+deb8u1_i386.deb ...
Unpacking gir1.2-poppler-0.18 (0.26.5-2+deb8u1) ...
Selecting previously unselected package liblept4.
Preparing to unpack .../liblept4_1.71-2.1+b2_i386.deb ...
Unpacking liblept4 (1.71-2.1+b2) ...
Selecting previously unselected package libtesseract3.
Preparing to unpack .../libtesseract3_3.03.03-1_i386.deb ...
Unpacking libtesseract3 (3.03.03-1) ...
Selecting previously unselected package tesseract-ocr-eng.
Preparing to unpack .../tesseract-ocr-eng_3.02-2_all.deb ...
Unpacking tesseract-ocr-eng (3.02-2) ...
Selecting previously unselected package tesseract-ocr-osd.
Preparing to unpack .../tesseract-ocr-osd_3.02-2_all.deb ...
Unpacking tesseract-ocr-osd (3.02-2) ...
Selecting previously unselected package tesseract-ocr-equ.
Preparing to unpack .../tesseract-ocr-equ_3.02-2_all.deb ...
Unpacking tesseract-ocr-equ (3.02-2) ...
Selecting previously unselected package tesseract-ocr.
Preparing to unpack .../tesseract-ocr_3.03.03-1_i386.deb ...
Unpacking tesseract-ocr (3.03.03-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up libopenjp2-7:i386 (2.1.0-2) ...
Setting up gir1.2-poppler-0.18 (0.26.5-2+deb8u1) ...
Setting up liblept4 (1.71-2.1+b2) ...
Setting up libtesseract3 (3.03.03-1) ...
Setting up tesseract-ocr-eng (3.02-2) ...
Setting up tesseract-ocr-osd (3.02-2) ...
Setting up tesseract-ocr-equ (3.02-2) ...
Setting up tesseract-ocr (3.03.03-1) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
~$ paperwork
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in 'locale/de/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/de/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/de/LC_MESSAGES/paperwork.mo' ...
WARNING paperwork.paperwork            WARNING: Locales not found
INFO   paperwork.backend.config       Config file not found. Will use '/home/sampablokuper/.config/paperwork.conf'
INFO   paperwork.backend.config       Reloading /home/sampablokuper/.config/paperwork.conf ...
ERROR  paperwork.frontend.util.config Warning: Failed to figure out system language (locale is [en_GB]). Will default to eng
ERROR  paperwork.frontend.util.config Exception was: 'alpha2'
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/home/sampablokuper/.local/bin/paperwork", line 6, in <module>
    main()
  File "/home/sampablokuper/.local/lib/python2.7/site-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/home/sampablokuper/.local/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 1869, in __init__
    self.__advanced_app_menu = self.__init_app_menu(self.app)
  File "/home/sampablokuper/.local/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2353, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/home/sampablokuper/.local/lib/python2.7/site-packages/paperwork/frontend/util/__init__.py", line 74, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
```

**Comment by arwarw** [comment] 2016-11-14 16:12
Same error, on Debian wheezy.
Some `~/.local/lib/python3.5/site-packages/usr/share/paperwork/mainwindow/appmenu.xml` exists, it just doesn't find it.

```
1708[arw@warp:~]# .local/bin/paperwork
WARNING paperwork.paperwork            No suitable localization file found.
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_8o3v00vn/pipe_c2s | /tmp/pyinsane_8o3v00vn/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file not found. Will use '/home/arw/.config/paperwork.conf'
INFO   paperwork_backend.config       Reloading /home/arw/.config/paperwork.conf ...

(paperwork:10829): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(paperwork:10829): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(paperwork:10829): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File ".local/bin/paperwork", line 6, in <module>
    main()
  File "/home/arw/.local/lib/python3.5/site-packages/paperwork/paperwork.py", line 118, in main
    main_win = MainWindow(config)
  File "/home/arw/.local/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2075, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/home/arw/.local/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2618, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/home/arw/.local/lib/python3.5/site-packages/paperwork/frontend/util/__init__.py", line 84, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
```

**Comment by arwarw** [comment] 2016-11-14 16:29
It works if I cd to `/home/arw/.local/lib/python3.5/site-packages/usr/share/paperwork`, which means that either the initialisation should chdir there or all paths for resources should use the proper installation prefix, e.g. in `/home/arw/.local/lib/python3.5/site-packages/usr/share/paperwork` line 2618 where this error comes from.

**Comment by jflesch** [comment] 2016-11-14 16:50
Nah, it works because it looks for files in multiple locations, the first one being '.' (useful when in development).
From what you describe, it looks like ```sys.prefix``` isn't set correctly.
From what you describe I assume you installed Paperwork from virtualenv. Are you running it too from virtualenv ?

BTW, please do not comment on ticket closed and targetted at versions already released. Please open a new ticket.

**Comment by jflesch** [comment] 2016-11-14 17:04
Actually, it seems @sampablokuper and you didn't use the same install method than @sigmahlm . So yeah, we are not talking about the same thing.

In his case, Pip installed the data files in a weird location.
In the case of @sampablokuper (and I assume you), you installed Paperwork with ```pip3 install --user```, which is a method I have never tested yet.

**Comment by arwarw** [comment] 2016-11-14 17:11
> In the case of @sampablokuper (and I assume yours), you installed Paperwork with pip3 install --user

Yes, I did.
