### ISSUE TITLE
Thumbnails not switched when drag-n-Drop rearranging pages

### ISSUE THREAD

**Issue by scubbx** [jflesch/paperwork#366] opened 2015-01-30 22:23 UTC
When rearranging single pages of one document after it has been scanned page-by-page, the thunbnail preview still reflects the original ordering. But when clicking on one thumbnail, the newly arranged order is used. (-> also switch the naming of the thumbnail files when changing order)

Interestingly, the "main" thumbnail in the documents list always shows the correct thumbnail of the first page.

**Comment by scubbx** [comment] 2015-01-30 23:32
I might have filed the bug-report pematurely - with other documents it is working. I will watch the behaviour and report back.

**Comment by jflesch** [comment] 2015-01-31 09:35
It's actually quite possible. I think I saw the same bug sometimes, but I've never been able to reproduce it to debug it ...
Anyway, with #356 , there will be major UI changes, and I think I will have to rewrite this part. So unless you find a way to reproduce it almost systematically, I'm not sure if I'll fix it or just finish #356 first.

**Comment by CyrilBrulebois** [comment] 2015-02-17 03:49
In its simplest form, scan 3 pages from an ADF, select page 3, move it between 1 and 2. It triggers this bug all the time for me: no refresh of the thumbnails but the pages are correctly ordered (the move is taken into account) as seen when clicking on each and every page, or when exporting to an external PDF file.

(All of this using 74d47c72ae15afdc38c9723a98012948aa43f42a)

**Comment by jflesch** [comment] 2016-12-01 13:54
Note to myself : It is probably related to the size of the page displayed. In other word, internally, see if we use the cached thumbnail or if we recompute the image from the big one. I have a feeling that Paperwork may not be moving/deleting the cached thumbnail as it should.

**Comment by jflesch** [comment] 2016-12-05 10:10
I can't reproduce it :/ (1.0.6) (I only found an uncaughted exception that shouldn't make any real trouble)

So I will need the logs. You can get them using the diagnostic dialog ( https://openpaper.work/fr/helpdesk/kb/1/ ).
Please do update to 1.0.6 first (logs will be more complete ; uncaught exceptions weren't loggued before).

**Comment by jflesch** [comment] 2017-01-03 22:18
ping ?

**Comment by CyrilBrulebois** [comment] 2017-01-04 00:08
Unfortunately I don't have access to the scanning hardware right now (and won't have for a while), so feel free to close this as fixed/not reproducible (as far as I'm concerned); I'll open up a fresh bug report if I hit this again with a current version once I'm back to scanning stuff.

**Comment by jflesch** [comment] 2017-01-04 09:37
Ok. I'll wait for @scubbx feedback too first.

**Comment by scubbx** [comment] 2017-01-04 13:05
Since the original bug report, there have been released new versions of Paperwork and I also did a fresh install on my system, so the circumstances of the original bug report have changed considerably.
I did not yet reorder any other pages, so I did not stumble upon this bug again.

**Comment by jflesch** [comment] 2017-01-04 15:34
Hm, ok. I'm going to close this ticket then. Please comment if you get this bug again, and I'll reopen this ticket.

**Closed by jflesch** 2017-01-04 15:34 UTC
Labels: bug, need more info
