### ISSUE TITLE
Portable documents solution ?

### ISSUE THREAD

**Issue by fdev31** [jflesch/paperwork#442] opened 2016-02-17 12:48 UTC
Just an Idea, what do you think about the portable desktop idea:
- A USB stick always on you
- All your docs & main apps here
- Bootable directly or via VM

I'm working on something like that, based on archlinux, I'm giving paperwork a try with it.
You may fork it for a minimal "paperwork linux distribution" or contribute or whatever, currently it's alpha software but I may keep working on it.
You can clone/try it here https://github.com/fdev31/archx , unfortunately there is no downloadable disk image yet.

**Comment by jflesch** [comment] 2016-02-17 12:57
You can do it if you want, but it's out of the scope of Paperwork

**Comment by fdev31** [comment] 2016-02-17 13:19
Ok, there is some issues with default dependencies on arch currently but Ill give it a try... it sounds a good way to test the software as well ;) [cf. linuxfr #yesIknow]

**Comment by jflesch** [comment] 2016-02-17 13:20
Have fun :)
(Since this ticket is not a bug report of feature request, I'm going to close it ; we can continue the discussion on the mailing-list if you want)

**Closed by jflesch** 2016-02-17 13:20 UTC
