### ISSUE TITLE
Exception was: 'alpha2'

### ISSUE THREAD

**Issue by markmaas** [jflesch/paperwork#447] opened 2016-02-19 07:06 UTC
Dear Reader,

Tried the installation on a Ubuntu 14.04 machine:

```
mark@enterprise:~$ paperwork
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file not found. Will use '/home/mark/.config/paperwork.conf'
INFO   paperwork.backend.config       Reloading /home/mark/.config/paperwork.conf ...
ERROR  paperwork.frontend.util.config Warning: Failed to figure out system language (locale is [en_US]). Will default to eng
ERROR  paperwork.frontend.util.config Exception was: 'alpha2'
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1859, in __init__
    self.__init_headerbars()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2288, in __init_headerbars
    default_layout = settings.get_property("gtk-decoration-layout")
TypeError: object of type `GtkSettings' does not have property `gtk-decoration-layout'
mark@enterprise:~$
```

Not really sure what to do next really ;-)

**Comment by dfadeur** [comment] 2016-02-19 08:31
same issue on Mint 17.3

**Comment by jflesch** [comment] 2016-02-19 08:54
Duplicate of #441 #440 #439 .

As mentioned in one of the tickets, the latest version of Paperwork working on your distribution is Paperwork 0.2.5.

**Closed by jflesch** 2016-02-19 08:54 UTC
