### ISSUE TITLE
paperwork-chkdeps  [ERROR] Expected python 2.7 ! Got python 3.4.3.final.0

### ISSUE THREAD

**Issue by k3ck3c** [jflesch/paperwork#461] opened 2016-03-06 13:11 UTC
Ubuntu 14.04

$ which python
/usr/bin/python
$ python --version
Python 2.7.6

Installation went fine, if I launch paperwork I get

$ paperwork
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python3.4/dist-packages/paperwork/paperwork.py", line 26, in <module>
    gi.require_version('Poppler', '0.18')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Poppler not available
$ 

Any clues?

**Comment by k3ck3c** [comment] 2016-03-09 19:15
if I launch the same commands with 

strace paperwork-chkdeps

I get at the end

open("/usr/lib/girepository-1.0/Gtk-3.0.typelib", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=597240, ...}) = 0
mmap(NULL, 597240, PROT_READ, MAP_PRIVATE, 5, 0) = 0x7fadb4b90000
close(5)                                = 0
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
munmap(0x7fadb4b90000, 597240)          = 0
munmap(0x7fadb4c22000, 582964)          = 0
openat(AT_FDCWD, "/usr/lib/girepository-1.0", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
getdents(4, /* 89 entries */, 32768)    = 3720
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "[\33[31mERROR\33[0m] Expected python"..., 64[ERROR] Expected python 2.7 ! Got python 3.4.3.final.0
) = 64
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fadb9d6a340}, {0x46f178, [], SA_RESTORER, 0x7fadb9d6a340}, 8) = 0
close(3)                                = 0
exit_group(2)                           = ?
+++ exited with 2 +++
$

**Comment by jflesch** [comment] 2016-03-09 23:14
1) At one point, you run 'paperwork', and at the other 'strace paperwork-chkdeps' ? why ?
2) Paperwork >= 0.3.x won't run on Ubuntu LTS. Paperwork needs Gtk 3.14, and Ubuntu LTS only provides Gtk 3.10 (or 3.12, I don't remember exactly). I think this ticket is likely going to be a duplicate of #447 #443 #441 #440 .

**Comment by k3ck3c** [comment] 2016-03-10 04:56
1) just to give more information
2) so I will install 0.2.5

Thanks

**Comment by jflesch** [comment] 2016-03-12 17:05
I'm going to close this issue. I can reopen it later if you still have problems.

**Closed by jflesch** 2016-03-12 17:05 UTC
