### ISSUE TITLE
TypeError: object of type `GtkSettings' does not have property `gtk-decoration-layout'

### ISSUE THREAD

**Issue by sametmax** [jflesch/paperwork#441] opened 2016-02-17 08:04 UTC
Ubuntu 14.04: 
```
$ paperwork
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file not found. Will use '/home/user/.config/paperwork.conf'
INFO   paperwork.backend.config       Reloading /home/user/.config/paperwork.conf ...
ERROR  paperwork.frontend.util.config Warning: Failed to figure out system language (locale is [fr_FR]). Will default to eng
ERROR  paperwork.frontend.util.config Exception was: 'alpha2'
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/home/user/.local/lib/python2.7/site-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/home/user/.local/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 1859, in __init__
    self.__init_headerbars()
  File "/home/user/.local/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2288, in __init_headerbars
    default_layout = settings.get_property("gtk-decoration-layout")
TypeError: object of type `GtkSettings' does not have property `gtk-decoration-layout'
```

**Comment by jflesch** [comment] 2016-02-17 09:39
Duplicate of #440

**Closed by jflesch** 2016-02-17 09:39 UTC
