### ISSUE TITLE
No menu bar

### ISSUE THREAD

**Issue by rasatdev** [jflesch/paperwork#435] opened 2016-01-26 20:46 UTC
I installed both in Arch Linux and Linux Mint. The menu bar does not appear except "Paperwork". In your earlier screenshots its shows: "Document Page Editor Display Help". Without "Document" I was not able to import, one of the main features what I need. Also "New Document" icon doesn't give import but export.

**Comment by jflesch** [comment] 2016-01-26 21:48
That's not a bug, it's a feature.

Menu bar are deprecated in Gnome applications.
They are replaced by application menus (at the top of the screen in Gnome 3).

If you're not using Gnome, in the title bar /tool bar, you should have an extra button. This button has the icon of Paperwork, and gives access to the application menu.

**Comment by jflesch** [comment] 2016-01-26 21:49
The screenshots you saw are probably from 0.2 (branch 'stable'). You can have a look [here for the screenshots of 0.3](https://github.com/jflesch/paperwork/tree/testing).

**Comment by jflesch** [comment] 2016-01-26 21:50
By the way, the 'import' options are right beside the 'scan' button (top right of the window).

**Comment by jflesch** [comment] 2016-01-26 22:21
I'm going to close this issue. Please reopen if you still have problems.

**Closed by jflesch** 2016-01-26 22:21 UTC
