### ISSUE TITLE
no "Delete / Modify" button with imported doc 

### ISSUE THREAD

**Issue by fabrice-regnier** [jflesch/paperwork#599] opened 2017-02-17 15:15 UTC
Hi,

When i scan a doc, i can see the 2 buttons 'Delete / Modify' on the right of the screen.
![delete_modify_button](https://cloud.githubusercontent.com/assets/12799446/23070646/0e86e44a-f52c-11e6-8447-b7371d785fdf.png)

But when i import pdf (no scan), i can't see this button. May be it's a feature and not a bug. But, in this case, how could i turn it to left/right ?

regards,

f.

**Comment by tYYGH** [comment] 2017-02-17 19:41
By design, PDF imports are not changeable. While this should remain true in the future, a workaround is being thought of: #495

**Comment by jflesch** [comment] 2017-02-18 16:01
Yep, duplicate of #495 . --> Closed.

**Closed by jflesch** 2017-02-18 16:01 UTC
