### ISSUE TITLE
doesn't work on ubuntu 16.10

### ISSUE THREAD

**Issue by obrowny** [jflesch/paperwork#509] opened 2016-11-09 15:18 UTC
paperwork is a great software but it does'nt work with ubuntu 16.10 : 

```paperwork-shell chkdeps paperwork_backend```

returns : 
```
Traceback (most recent call last):
  File "/usr/local/bin/paperwork-shell", line 174, in <module>
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/local/bin/paperwork-shell", line 126, in chkdeps
    _chkdeps(module_name, distribution)
  File "/usr/local/bin/paperwork-shell", line 72, in _chkdeps
    missing = module.find_missing_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/paperwork_backend/deps.py", line 80, in find_missing_dependencies
    missing += check_python_version()
  File "/usr/local/lib/python2.7/dist-packages/paperwork_backend/deps.py", line 58, in check_python_version
    "Got python {}".format(".".join(python_ver))
TypeError: sequence item 0: expected string, int found
```

and the paperwork command returns : 
```Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 29, in <module>
    gi.require_version('Poppler', '0.18')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Poppler not available
```
Poppler is 0.44 in ubuntu 16.10
thanks !

**Comment by jflesch** [comment] 2016-11-09 15:46
I think this is a duplicate of #508 .
Basically, after the switch to Python 3, I forgot to update the install documentation. So you did try to start paperwork-shell with python 2.7 instead of 3. Sorry :/

I've fixed the documentation. If there are still a problem with the install instructions, please comment again here and I'll reopen the ticket.

**Closed by jflesch** 2016-11-09 15:46 UTC
Labels: bug
