### ISSUE TITLE
paperwork_backend.util and Unknown language [eng]. Switching back to english

### ISSUE THREAD

**Issue by ledshark24** [jflesch/paperwork#510] opened 2016-11-09 18:49 UTC
Hi,

I tried installing on Ubuntu 16.04 following https://github.com/jflesch/paperwork/blob/stable/doc/install.debian.markdown and I have used paperwork-shell to install extra deps for both paperwork_backend and paperwork

But when I launch paperwork it fails after quite a verbose list of the same warnings (last one repeats a lot) : 
```
WARNING paperwork_backend.util         Unknown language [fr]. Switching back to english
WARNING paperwork_backend.util         Unknown language [eng]. Switching back to english
WARNING paperwork_backend.util         Unknown language [eng]. Switching back to english
WARNING paperwork_backend.util         Unknown language [eng]. Switching back to english
```
how can I fix this (or what did I miss) ?
Thanks in advance :)

**Comment by Pafzedog** [comment] 2016-11-09 21:51
Hello,

Same OS version, similar installation process, similar errors .

here is full stderr output 
[paperwork_error.txt](https://github.com/jflesch/paperwork/files/581905/paperwork_error.txt)

**Comment by jflesch** [comment] 2016-11-09 22:11
Weird. This bug is probably related to the latest version of pycountry. I'm going to give it a try.

**Comment by jflesch** [comment] 2016-11-09 22:16
Can you give me the output of ```pip3 show pycountry``` please ?

**Comment by jflesch** [comment] 2016-11-09 22:24
Ok, nevermind, I've reproduced the bug

**Comment by jflesch** [comment] 2016-11-09 22:37
Fix:
https://github.com/jflesch/paperwork-backend/commit/c79b0a67e37e9c969cbc55f373b7fe07bd363b00
https://github.com/jflesch/paperwork/commit/1bd37b4f456d7d538c43e0ea7142ff15692ced45

I would appreciate if you could try it on your side:

```
cd ~/git
git clone https://github.com/jflesch/paperwork-backend.git
git clone https://github.com/jflesch/paperwork.git
(cd paperwork-backend && git checkout stable && sudo python3 ./setup.py install)
(cd paperwork && git checkout stable && sudo python3 ./setup.py install)
```

**Comment by jflesch** [comment] 2016-11-09 23:35
Since I'm fairly certain it should fix your problem and that others will have it, I've released a new version with the fix (Paperwork 1.0.1).
If you installed Paperwork with pip3, the simplest way to update is ```sudo pip3 install -U paperwork```.

**Comment by Pafzedog** [comment] 2016-11-10 17:44
Well done ! 
It works for me now :)

**Comment by jflesch** [comment] 2016-11-10 18:04
Awesome :)
I'm closing this ticket. Please comment again here if you need it reopened

**Closed by jflesch** 2016-11-10 18:04 UTC
Labels: blocking, bug
