### ISSUE TITLE
Error: index locked

### ISSUE THREAD

**Issue by Jonny007-MKD** [jflesch/paperwork#483] opened 2016-06-04 15:02 UTC
Hi,

I've added labels and changed the date of an imported PDF. After click the "Back" button the left column loading icon keeps spinning.

This is the error I got (I removed the `Animators` lines):

    INFO   paperwork.frontend.util.actions Action: [Open selected document]
    INFO   paperwork.frontend.mainwindow.docs Showing doc 20160604_1308_32
    INFO   paperwork.frontend.mainwindow  Showing document 20160604_1308_32
    INFO   paperwork.frontend.mainwindow  Showing page 20160604_1308_32 p1
    INFO   paperwork.frontend.mainwindow  Showing document 20160604_1308_32
    INFO   paperwork.frontend.mainwindow  Showing page 20160604_1308_32 p1
    INFO   paperwork.frontend.mainwindow  Showing document 20160604_1308_32
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    (paperwork:7181): Gtk-WARNING **: /home/clem/Sandbox/gtk/./gtk/gtkwidget.c:4589: child-property-changed notification for GtkListBox(0x31b91e0) is not frozen
    INFO   paperwork.frontend.util.actions Action: [Set document date]
    INFO   paperwork.frontend.util.actions Action: [Switch back to doc list]
    INFO   paperwork.frontend.mainwindow.docs Checking for new labels
    INFO   paperwork.frontend.mainwindow.docs Apply new labels
    INFO   paperwork.frontend.mainwindow.docs Checking for new keywords
    ERROR  paperwork.frontend.util.jobs   ===> Job IndexUpdater:1 raised an exception: <class 'whoosh.index.LockError'>: 
    ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/jobs.py: L  178: _run
    ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py: L  379: do
    ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python2.7/dist-packages/paperwork/backend/docsearch.py: L  460: get_index_updater
    ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python2.7/dist-packages/paperwork/backend/docsearch.py: L  216: __init__
    ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python2.7/dist-packages/whoosh/index.py: L  464: writer
    ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python2.7/dist-packages/whoosh/writing.py: L  515: __init__
    ERROR  paperwork.frontend.util.jobs   ---> Job IndexUpdater:1 was started by:
    ERROR  paperwork.frontend.util.jobs    0: /usr/local/bin/paperwork: L    6: <module>
    ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py: L  114: main
    ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py: L   67: on_button_clicked_cb
    ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py: L   64: __do
    ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py: L  392: do
    ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py: L 1146: apply_properties
    ERROR  paperwork.frontend.util.jobs    6: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/jobs.py: L  247: schedule
    INFO   paperwork.frontend.util.canvas Animators: 1
    INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 0 documents [0-3]

I have no second instance of paperwork running. But I opened paperwork before, closed it quite immediately (while it was loading the documents) and started it again from the terminal. Perhaps the lock isn't removed when exiting during startup?

**Comment by jflesch** [comment] 2016-06-29 11:35
Did you check with ```ps``` that you don't have any paperwork process remaining in the background ?

I have this exception sometimes. Usually, here is what happens when it happens to me:

- I start Paperwork
- For some reason, it rebuild the index from scratch (I keep switching between version stable and unstable, so it has to)
- The rebuild last too long, so I close Paperwork
- The main window disappear, but the process of Paperwork remains in Paperwork (known bug ; don't know why yet)
- I try to start a new instance of Paperwork, and I get this exception

**Comment by Jonny007-MKD** [comment] 2016-06-30 22:45
Well, it's been a few days since then, but I remember being absolutely sure that no other instance was running. I know of `ps` and `top`. 
Somehow I fixed it. I think I deleted some lock file(s) in the index directory.

**Comment by jflesch** [comment] 2016-07-01 11:26
Hm, weird. Anyway, since neither you or me are able to reproduce this issue anymore, I have to close it.
If you (or someone) else can reproduce it again, please comment on this ticket, and I will reopen it.

**Closed by jflesch** 2016-07-01 11:26 UTC
Labels: bug, to study
