### ISSUE TITLE
Editing after changing docid fails

### ISSUE THREAD

**Issue by Jonny007-MKD** [jflesch/paperwork#484] opened 2016-06-21 11:10 UTC
I've changed the date of a document (the docid) and returned to the overview. Then I selected the document again and changed the labels and the extra text. Saving this information fails:

    INFO   paperwork.backend.docsearch    Removing doc from the index: 20160621_1256_31
    INFO   paperwork.backend.docsearch    Index: Commiting changes
    INFO   paperwork.backend.common.doc   Changing docid: /j/Sync/Dokumente/Paperwork/papers/20160621_1256_31 -> /j/Sync/Dokumente/Paperwork/papers/20160620_0000_01
    INFO   paperwork.frontend.mainwindow  Searching: []
    INFO   paperwork.frontend.mainwindow.docs Got 134 documents
    INFO   paperwork.frontend.util.actions Action: [Open selected document]
    INFO   paperwork.backend.docsearch    Indexing new doc: 20160620_0000_01
    INFO   paperwork.backend.docsearch    Index: Commiting changes
    INFO   paperwork.frontend.mainwindow  Searching: []
    INFO   paperwork.frontend.mainwindow.docs Got 135 documents
    INFO   paperwork.frontend.util.actions Action: [Open selected document]
    INFO   paperwork.frontend.mainwindow.docs Showing doc 20160620_0000_01
    INFO   paperwork.frontend.mainwindow  Doc is already shown
    INFO   paperwork.frontend.util.actions Action: [Switch back to doc list]
    
    INFO   paperwork.frontend.mainwindow.docs Checking for new labels
    INFO   paperwork.frontend.mainwindow.docs Apply new labels
    Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 67, in on_button_clicked_cb
            return self.__do()
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 64, in __do
            return self.do(**kwargs)
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 392, in do
            self.__main_win.doc_properties_panel.apply_properties()
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 1111, in apply_properties
            self.doc.labels = new_labels
        File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/common/doc.py", line 186, in __set_labels
            encoding='utf-8') as file_desc:
        File "/usr/lib/python2.7/codecs.py", line 878, in open
            file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/j/Sync/Dokumente/Paperwork/papers/20160621_1256_31/labels'
    
    INFO   paperwork.frontend.mainwindow.docs Apply new keywords
    Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 67, in on_button_clicked_cb
            return self.__do()
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 64, in __do
            return self.do(**kwargs)
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 392, in do
            self.__main_win.doc_properties_panel.apply_properties()
        File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 1124, in apply_properties
            self.doc.extra_text = new_extra_text
        File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/common/doc.py", line 386, in __set_extra_text
            encoding='utf-8') as file_desc:
        File "/usr/lib/python2.7/codecs.py", line 878, in open
            file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/j/Sync/Dokumente/Paperwork/papers/20160621_1256_31/extra.txt'

The `IOErrors` show that the old docid is used to access the `label`  and `extra.txt` files.

**Comment by jflesch** [comment] 2016-06-29 12:17
I think this is a duplicate of #457.
If not, please comment and I will reopen.

**Closed by jflesch** 2016-06-29 12:17 UTC
Labels: bug
