### ISSUE TITLE
docker image not working on Kubuntu 15.04

### ISSUE THREAD

**Issue by BogusLogin** [jflesch/paperwork#472] opened 2016-04-17 18:13 UTC
I installed docker and ran the docker command form the wiki. I got the the same error message described in the [wiki](https://github.com/jflesch/paperwork/blob/stable/doc/install.docker.markdown) and so I entered `xhost local:root`. This also resolved the problem on Kubuntu 14.04 for me.

Unfortunately the docker command failed and returned:

(paperwork:19): Gtk-WARNING **: Could not load image 'paperwork.svg': Failed to open file '/usr/share/paperwork/mainwindow/paperwork.svg': No such file or directory

(paperwork:19): Gdk-ERROR **: The program 'paperwork' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 157 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

(I didn't include the whole log so I temporarily put it on [pastebin](http://pastebin.com/GySSCqNP))
Any help appreciated!

**Comment by jflesch** [comment] 2016-04-17 18:26
@tclavier  ?

**Comment by tclavier** [comment] 2016-04-18 05:56
Hello,

I just test on my debian and that work fine with this error log : 

```
** (paperwork:23): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-7oU9pJk0yH: Connection refused
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file found: /home/tom/.config/paperwork.conf
INFO   paperwork.backend.config       Reloading /home/tom/.config/paperwork.conf ...
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.frontend.util        CSS file used: /usr/share/paperwork/application.css
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade

(paperwork:23): Gtk-WARNING **: Could not load image 'paperwork.svg': Failed to open file '/usr/share/paperwork/mainwindow/paperwork.svg': No such file or directory
```

IMHO error start at line 36 of your pastebin. The command in documentation : 

```
docker run -ti --rm \
  -e DISPLAY=$DISPLAY -e XAUTHORITY=$HOME/.Xauthority -e HOME=$HOME -e USER=$USER \
  -v $HOME:$HOME -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/sane.d/:/etc/sane.d/ \
  tclavier/paperwork
```

suppose you had your Xauthority is in your home and X11 unix socket is in /tmp/.X11-unix/ ... and in Kubuntu it's probably false. Could you test with this start command they load Xauthority from env :+1: 

```
docker run -ti --rm \
  -e DISPLAY=$DISPLAY -e XAUTHORITY=$HOME/.Xauthority -e HOME=$HOME -e USER=$USER \
  -v $HOME:$HOME -v $XAUTHORITY:$HOME/.Xauthority  -v /tmp/.X11-unix:/tmp/.X11-unix \
  tclavier/paperwork
```

**Comment by BogusLogin** [comment] 2016-04-18 14:33
Hi tclavier, thx for your help.

I ran the command and compared it with my pastebin snippet. The only difference now is, that the line `
** (paperwork:19): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-fcCKzraRvf: Connection refused`
went away, but it's still crashing!

**Comment by tclavier** [comment] 2016-04-18 19:07
The problem is more complicated  ... it's possible to run :
- `ls -la /tmp/.X11-unix/`
- `env | grep X`

**Comment by BogusLogin** [comment] 2016-04-19 20:02
first command yields:
```
total 8
drwxrwxrwt  2 root root 4096 Apr 19 18:42 .
drwxrwxrwt 17 root root 4096 Apr 19 21:58 ..
srwxrwxrwx  1 root root    0 Apr 19 18:42 X0
```
2nd command yields:
```
XDG_SESSION_COOKIE=2eb692d472634e68a9ddf4-c3-14684158.167208-120586719
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_ID=2
XDG_CURRENT_DESKTOP=KDE
SSH_AUTH_SOCK=/tmp/ssh-Dvk29lkmqX3e/agent.1222
XDG_SESSION_DESKTOP=KDE
XDG_DATA_DIRS=/usr/share/plasma:/usr/local/share/:/usr/share/
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_TYPE=x11
XDG_CONFIG_DIRS=/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
XCURSOR_THEME=breeze_cursors
XAUTHORITY=/tmp/xauth-1000-_0
XDG_SESSION_CLASS=user
XDG_SEAT=seat0
XDG_VTNR=7
```

**Comment by jflesch** [comment] 2016-05-09 13:40
ping ?

**Comment by tclavier** [comment] 2016-05-09 16:17
I can't reproduce the probleme, and I haven't the same X configuration as kubuntu. I will test with virtual box ...

**Comment by jflesch** [comment] 2016-05-09 16:36
It feels like it may be a problem due to Xorg / Wayland, no ? Which version of Debian and Ubuntu are you both running exactly ?

**Comment by jflesch** [comment] 2016-07-27 12:41
Ping ?

**Comment by tclavier** [comment] 2016-07-28 06:55
I just run the last debian sid, and yes it's a problem to handle communication to X server.

Could you close it ?

**Comment by jflesch** [comment] 2016-07-28 08:16
Ok

**Closed by jflesch** 2016-07-28 08:16 UTC
